### ISSUE TITLE
小程序内加入logo,二维码无法显示

### ISSUE THREAD

**Issue by JINqibin** [Sansnn/uQRCode#9]
开发工具内显示正常,但是真机无法显示
配置为 mode="canvas" file-type="png"

**Comment by Sansnn** [comment]
logo资源是否来自网络

**Comment by Sansnn** [comment]
小程序白名单是否配置

**Comment by JINqibin** [comment]
> logo 资源是否来自网络

我刚尝试了把示例项目放真机上跑,也是这个问题,和我有没有放logo没关系
在微信开发工具二维码可以显示,真机上二维码无法显示

**Comment by JINqibin** [comment]
我用的的git上的版本

**Comment by Sansnn** [comment]
机型提供一下

**Comment by JINqibin** [comment]
小米12

**Comment by JINqibin** [comment]
示例项目真机 mode="canvas" 的时候 二维码空白  调整小块圆角可以显示,但是这不是我想要的效果

**Comment by 35AhLin** [comment]
![image](https://user-images.githubusercontent.com/102887042/165477779-698a3434-02e7-4cde-b8e3-c46bf081c445.png)
添加图片不显示

**Comment by 35AhLin** [comment]
![image](https://user-images.githubusercontent.com/102887042/165478891-e4d1dc29-f394-47ef-9ff7-c716cc35a49d.png)
添加图片不显示什么原因

**Comment by JINqibin** [comment]
> ![image](https://user-images.githubusercontent.com/102887042/165478891-e4d1dc29-f394-47ef-9ff7-c716cc35a49d.png) 添加图片不显示什么原因
你用的什么版本是github的版本还是插件市场上的

**Comment by JINqibin** [comment]
> > ![image](https://user-images.githubusercontent.com/102887042/165478891-e4d1dc29-f394-47ef-9ff7-c716cc35a49d.png) 添加图片不显示什么原因
> > 你用的什么版本是github的版本还是插件市场上的
github上的版本高点多点但是Canvas模式有点问题,我用示例项目测试的,作者还未给出解决方案

**Comment by 35AhLin** [comment]
好像使用的是插件市场导入的 就一个文件






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sansnn/uQRCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月27日(星期三) 下午4:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sansnn/uQRCode] 小程序内加入logo,二维码无法显示 (Issue #9)





   
 添加图片不显示什么原因
 你用的什么版本是github的版本还是插件市场上的
 github上的版本高点多点但是Canvas模式有点问题,我用示例项目测试的,作者还未给出解决方案

**Comment by Sansnn** [comment]
两个老哥加下QQ群，695070434，我给你们看看

**Comment by JINqibin** [comment]
> 好像使用的是插件市场导入的 就一个文件
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sansnn/uQRCode" ***@***.***&gt;; 发送时间:&nbsp;2022年4月27日(星期三) 下午4:50 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Sansnn/uQRCode] 小程序内加入logo,二维码无法显示 (Issue #9) 添加图片不显示什么原因 你用的什么版本是github的版本还是插件市场上的 github上的版本高点多点但是Canvas模式有点问题,我用示例项目测试的,作者还未给出解决方案 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

哥,我看插件市场上的源码都没有foregroundImage这个属性可以设置图片,你仔细看看文档

**Comment by JINqibin** [comment]
> > 好像使用的是插件市场导入的 就一个文件
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Sansnn/uQRCode" _**@**_._**>; 发送时间: 2022年4月27日(星期三) 下午4:50 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [Sansnn/uQRCode] 小程序内加入logo,二维码无法显示 (Issue #9) 添加图片不显示什么原因 你用的什么版本是github的版本还是插件市场上的 github上的版本高点多点但是Canvas模式有点问题,我用示例项目测试的,作者还未给出解决方案 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 哥,我看插件市场上的源码都没有foregroundImage这个属性可以设置图片,你仔细看看文档
文档上的2个写法也不是你这样的

**Comment by 35AhLin** [comment]
这我就不知道怎么使用了 哈哈哈


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sansnn/uQRCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月27日(星期三) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sansnn/uQRCode] 小程序内加入logo,二维码无法显示 (Issue #9)





   
好像使用的是插件市场导入的 就一个文件
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sansnn/uQRCode" @.&gt;; 发送时间:&nbsp;2022年4月27日(星期三) 下午4:50 _@**._&gt;; ***@***.***@._&gt;; 主题:&nbsp;Re: [Sansnn/uQRCode] 小程序内加入logo,二维码无法显示 (Issue #9) 添加图片不显示什么原因 你用的什么版本是github的版本还是插件市场上的 github上的版本高点多点但是Canvas模式有点问题,我用示例项目测试的,作者还未给出解决方案 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _@_.*&gt;
  
哥,我看插件市场上的源码都没有foregroundImage这个属性可以设置图片,你仔细看看文档
 文档上的2个写法也不是你这样的

**Comment by JINqibin** [comment]
> 两个老哥加下QQ群，695070434，我给你们看看

加群了
